### 
GET http://localhost:3000/

###
POST http://localhost:3000/
content-type: application/json

{
  "result": {
    "action": "sqrt",
    "parameters": {
      "number": 9
    }
  }
}

###
POST http://localhost:3000/
content-type: application/json

{
  "result": {
    "action": "AddNumbers",
    "parameters": {
      "number": [9,8,9]
    }
  }
}

###