### 
GET http://localhost:3000/
Authorization: Basic user password
###
POST http://localhost:3000/api
content-type: application/json
Authorization: Basic user password

{
  "result": {
    "action": "sqrt",
    "parameters": {
      "number": 9
    }
  }
}

###
POST http://localhost:3000/api
content-type: application/json
Authorization: Basic user password

{
  "result": {
    "action": "AddNumbers",
    "parameters": {
      "number": [9,8,9]
    }
  }
}

###